### ISSUE TITLE
Bad error message when Q doesn't exist.

### ISSUE THREAD

**Issue by drewlarson1** [F3Nation-Community/PAXminer#18] opened 2024-02-01 18:26 UTC
My PAX was DR. He copied and pasted the backblast from the other region into our DR channel. Paxminer didn't recognize the Q (didn't exist) and so it started harassing him. 

When Q doesn't exist, finish processing Backblast (PAX, AO, Count) and send author ONE message that Q doesn't exist. Then stop.

Note: at present, we are working to resolve this issue with the use of Syncbot. But, would be nice if the Paxminer politely and pleasantly in this case.

Griswold, F3xT

**Comment by farrellw** [comment] 2024-02-13 03:15
@drewlarson1, thanks for submitting the issue. 

Right now, the message sent back to the user is:

```
ERROR: The Q is not present or not tagged correctly. Please ensure the Q is tagged using @PAX_NAME
```

That seems like a pretty good message to me. How do you think it could be better?

**Comment by farrellw** [comment] 2024-04-26 20:41
By the conetxt of this message, it seems a duplicate of the other harrrassing Q mesage. Which was solved by the 1 time a day message.

**Closed as completed** 2024-04-26 20:41 UTC
